### PR TITLE
fix: update config to work with new version of hedera-json-rpc-relay

### LINKED ISSUE #244: Ensure JSON RPC relay is usable
`solo` allows us to deploy relays using command `solo relay deploy -i node0,node1,node2`. We need to ensure that the deployed relay is actually usable. 

I have attempted run an existing smoke test that runs query through the relay, but so far it didn't work. 

Here is how ran the test:

1. Deploy network and relays using `solo`(https://www.notion.so/swirldslabs/Technical-Workshop-Solo-8818724b161a4d7a970f48b840952d71)
2. Expose Hedera Explorer and ensure transactions and accounts are visible (https://www.notion.so/swirldslabs/Technical-Workshop-Solo-8818724b161a4d7a970f48b840952d71?pvs=4#79bf814ca85f4ae3b3bd13d127e8899b)
3. Expose a network-node-svc:50211 port
4. Expose relay port: 7546
5. Clone `https://github.com/hashgraph/hedera-local-node`
   5a.  Run `npm install`
   5b. Run `npm run generate-accounts 3` that would generate 3 keys with title `Accounts list (Alias ECDSA keys)`
   5c. Update `test/smoke/hardhat.config.js` with two account private keys from the  `Alias ECDSA keys` generated in step 5b
6. Go into test/smoke and run `npm install` and then run `npx hardhat test`

Ideally the smoke test should pass. However I am getting error like below:

```
➜  smoke git:(main) ✗ npx hardhat test
WARNING: You are currently using Node.js v21.7.1, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions




  Smoke Tests
    Relay
      1) Should perform a crypto transfer transaction
    Websocket server
      2) "before all" hook for "Should receive events for subscribed contract"


  0 passing (3s)
  2 failing

  1) Smoke Tests
       Relay
         Should perform a crypto transfer transaction:
     ProviderError: [Request ID: ab106718-64b1-4796-874a-02de4fd5df3b] Error invoking RPC: queryA and queryAaaa ENODATA fullstack-deployment-rest
      at HttpProvider.request (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/node_modules/hardhat/src/internal/core/providers/http.ts:90:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at HardhatEthersProvider.getBalance (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:171:21)
      at Context.<anonymous> (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/test/Smoke.js:17:39)

  2) Smoke Tests
       Websocket server
         "before all" hook for "Should receive events for subscribed contract":
     ProviderError: [Request ID: 48b12f92-c683-4d70-a790-5c2c38cff33e] Unknown error invoking RPC
      at HttpProvider.request (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/node_modules/hardhat/src/internal/core/providers/http.ts:90:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at HardhatEthersProvider.getBlockNumber (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:134:25)
      at HardhatEthersSigner.sendTransaction (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:122:25)
      at ContractFactory.deploy (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/node_modules/ethers/src.ts/contract/factory.ts:111:24)
      at Context.<anonymous> (/Users/leninmehedy/code/src/github.com/hashgraph/hedera-local-node/test/smoke/test/Smoke.js:39:16)

```

I have asked for help from mirror-node and hedera-local-node team and awaiting/trying the suggestions.

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

* updated version of using rpc replay
* updated to work with new rcp relay version
* only tested with latest rcp relay repo by downloading to local laptop, not being able to test released version since the release process of `hedera-json-rpc-relay` is broken
* Adding new function getNodeAccountMap and prepareNetworkJsonString

### Related Issues

* #244

### Cannot merge yet since relay test would fail because the config is not working with latest published old version 0.26,
will only work with 0.48 or later, need to wait `hedera-json-rpc-relay` chart release process fixed first:

https://github.com/hashgraph/hedera-json-rpc-relay/issues/2506

### CODE REVIEW

File: src/commands/relay.mjs [hunk 1]
```diff
@@ -70,8 +72,8 @@ export class RelayCommand extends BaseCommand {
     }
 
     nodeIDs.forEach(nodeID => {
-      const networkKey = `network-${nodeID.trim()}-0:50211`
-      valuesArg += ` --set config.HEDERA_NETWORK.${networkKey}=0.0.3`
+      const networkKey = `network-${nodeID.trim()}:50211`
+      valuesArg += ` --set config.HEDERA_NETWORK='{"${networkKey}":"0.0.3"}'`
```
Comment (leninmehedy) [inline src/commands/relay.mjs:76]: It needs to be different account for different node. 

This is where we currently associate a node to an account: https://github.com/hashgraph/solo/blob/main/src/core/profile_manager.mjs#L151

We need to do similar here. So probably we need to create a helper function that returns a map of nodeID -> accountID that can be used both places.

Comment (JeffreyDallas) [reply src/commands/relay.mjs]: Updated

File: src/commands/relay.mjs [hunk 2]
```diff
@@ -69,12 +72,35 @@ export class RelayCommand extends BaseCommand {
...
+  }
+
+  // created a json string to represent the map between the node keys and their ids
+  // output example '{"node-1": "0.0.3", "node-2": "0.004"}'
+  prepareNetworkJsonString (nodeIDs = []) {
+    if (!nodeIDs) {
+      throw new MissingArgumentError('Node IDs must be specified')
+    }
+
+    let jsonString = '{'
```
Comment (leninmehedy) [inline src/commands/relay.mjs:87]: Instead of the creating a json string, create an object first and then just use `JSON.stringify`.

Comment (JeffreyDallas) [reply src/commands/relay.mjs]: Changed to using JSON.stringify. Thanks

File: src/commands/relay.mjs [hunk 3]
```diff
@@ -69,12 +72,27 @@ export class RelayCommand extends BaseCommand {
...
+  }
+
+  // created a json string to represent the map between the node keys and their ids
+  // output example '{"node-1": "0.0.3", "node-2": "0.004"}'
+  prepareNetworkJsonString (nodeIDs = []) {
+    if (!nodeIDs) {
+      throw new MissingArgumentError('Node IDs must be specified')
+    }
+
+    const netWorkIds = {}
```
Comment (jeromy-cannon) [inline src/commands/relay.mjs:87]:
```suggestion
    const networkIds = {}
```

File: src/commands/relay.mjs [hunk 4]
```diff
@@ -69,12 +72,27 @@ export class RelayCommand extends BaseCommand {
...
+    const accountMap = getNodeAccountMap(nodeIDs)
+
     nodeIDs.forEach(nodeID => {
-      const networkKey = `network-${nodeID.trim()}-0:50211`
-      valuesArg += ` --set config.HEDERA_NETWORK.${networkKey}=0.0.3`
+      const networkKey = `network-${nodeID.trim()}:50211`
```
Comment (jeromy-cannon) [inline src/commands/relay.mjs:91]: `network-node0:50211` would point to the headless service for the network node.  

I think it would be better to use [accountManager.getNodeServiceMap(namespace)[(https://github.com/hashgraph/solo/blob/37d44f304510d29e8424683814960c707a7fa142/src/core/account_manager.mjs#L256-L256), as this would give you a map that would already give you the accountIds as read from the services [and more see link](https://github.com/hashgraph/solo/blob/37d44f304510d29e8424683814960c707a7fa142/src/core/network_node_services.mjs#L17-L17).   Also, it will give you the GRPC port in case it changes.  It can give you the IP address (haProxyClusterIp) and port (haProxyGrpcPort) of the HAProxy service, which I think is what you should be hitting.  Also, if you want to generate a service name we leverage the render functions in the templates.mjs.

**Comment by isavov** [comment]
@leninmehedy Update: https://github.com/hashgraph/hedera-json-rpc-relay/issues/2506 has been resolved

File: src/commands/relay.mjs (hunk 4 above)
Comment (JeffreyDallas) [reply src/commands/relay.mjs]: updated

File: src/commands/relay.mjs (hunk 3 above)
Comment (JeffreyDallas) [reply src/commands/relay.mjs]: updated

File: src/core/profile_manager.mjs [hunk 5]
```diff
@@ -148,15 +149,12 @@ export class ProfileManager {
   resourcesForConsensusPod (profile, nodeIds, yamlRoot) {
     if (!profile) throw new MissingArgumentError('profile is required')
 
-    // prepare name and account IDs for nodes
-    const realm = constants.HEDERA_NODE_ACCOUNT_ID_START.realm
-    const shard = constants.HEDERA_NODE_ACCOUNT_ID_START.shard
-    let accountId = constants.HEDERA_NODE_ACCOUNT_ID_START.num
+    const accountMap = getNodeAccountMap(nodeIds)
```
Comment (jeromy-cannon) [inline src/core/profile_manager.mjs:152]: there are some changes I'm introducing that will cause us to run this logic before the helm charts have been installed, so this command will fail.   Please revert for the change in this location.

File: src/commands/relay.mjs [hunk 6]
```diff
@@ -69,12 +75,30 @@ export class RelayCommand extends BaseCommand {
...
+    const networkIds = {}
+    const accountMap = getNodeAccountMap(nodeIDs)
+
+    const networkNodeServicesMap = await this.accountManager.getNodeServiceMap(namespace)
     nodeIDs.forEach(nodeID => {
-      const networkKey = `network-${nodeID.trim()}-0:50211`
-      valuesArg += ` --set config.HEDERA_NETWORK.${networkKey}=0.0.3`
+      const nodeName = networkNodeServicesMap.get(nodeID).nodeName
+      const haProxyGrpcPort = networkNodeServicesMap.get(nodeID).haProxyGrpcPort
+      const networkKey = `network-${nodeName}:${haProxyGrpcPort}`
```
Comment (jeromy-cannon) [inline src/commands/relay.mjs:97]: I would think we would want to run the relay through haProxy.
```suggestion
      const networkKey = `${haProxyClusterIp}:${haProxyGrpcPort}`
```

**Review by jeromy-cannon — APPROVED** [review]

File: src/core/profile_manager.mjs (hunk 5 above)
Comment (jeromy-cannon) [reply src/core/profile_manager.mjs:152]: I need your changes, so I'll just revert this in mine when I need it.
