### PR TITLE
fix: collect java process metrics during performance e2e tests

### LINKED ISSUE #3383: Collect JVM metrics during Performance tests

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
## Description

This PR adds a new flag to `solo consensus network deploy`: `--jfr-config`. It can be used to provide a path to a Java Flight Recorder configuration file to be uploaded to every consensus node. When such a file is provided, the node is started with additional JAVA_OPTS that start the recording process.

A new command is added to dump and download the recording: `solo consensus node collect-jfr`.

A new environment variable is added `JAVA_FLIGHT_RECORDER_CONFIGURATION`. It is used as a way to expose the `--jfr-config` flag functionality to `one-shot` without adding the flag to the command.

The `Performance E2E tests` are configured to utilize the new functionality, and the recording is uploaded to GitHub during the `Upload Metrics data and Chart to GitHub` step of the workflow.

### Related Issues

* Closes #3383 
* Related to #

### Pull request (PR) checklist

* \[ ] This PR added tests (unit, integration, and/or end-to-end)
* \[ ] This PR updated documentation
* \[ ] This PR added no TODOs or commented out code
* \[ ] This PR has no breaking changes
* \[ ] Any technical debt has been documented as a separate issue and linked to this PR
* \[ ] Any `package.json` changes have been explained to and approved by a repository manager
* \[ ] All related issues have been linked to this PR
* \[ ] All changes in this PR are included in the description
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been followed

### Testing

* \[ ] This PR added unit tests
* \[ ] This PR added integration/end-to-end tests
* \[ ] These changes required manual testing that is documented below
* \[ ] Anything not tested is documented

The following manual testing was done:

* TBD

The following was not tested:

* TBD

<details>
<summary>
Commit message guidelines
</summary>
We use 'Conventional Commits' to ensure that our commit messages are easy to read, follow a consistent format, and for automated release note generation. Please follow the guidelines below when writing your commit messages:

1. BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.  NOTE: currently breaking changes will only bump the MAJOR version.
2. The title is prefixed with one of the following:

| Prefix    | Description                                         | Semantic Version Update | Captured in Release Notes |
|-----------|-----------------------------------------------------|-------------------------|---------------------------|
| feat:     | a new feature                                       | MINOR                   | Yes                       |
| fix:      | a bug fix                                           | PATCH                   | Yes                       |
| perf:     | performance                                         | PATCH                   | Yes                       |
| refactor: | code change that isn't feature or fix               | none                    | No                        |
| test:     | adding missing tests                                | none                    | No                        |
| docs:     | changes to documentation                            | none                    | Yes                        |
| build:    | changes to build process                            | none                    | No                        |
| ci:       | changes to CI configuration                         | none                    | No                        |
| style:    | formatting, missing semi-colons, etc                | none                    | No                        |
| chore:    | updating grunt tasks etc; no production code change | none                    | No                        |

</details>

### CODE REVIEW

File: src/commands/node/config-interfaces/node-collect-jfr-logs-context.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// SPDX-License-Identifier: Apache-2.0
+
+import {type NodeCollectJFRLogsConfigClass} from './node-collect-jfr-logs-config-class.js';
+
+export interface NodeCollectJFRLogsContext {
```
Comment (jeromy-cannon) [inline src/commands/node/config-interfaces/node-collect-jfr-logs-context.ts]:
```suggestion
export interface NodeCollectJfrLogsContext {
```

File: src/commands/flags.ts [hunk 2]
```diff
@@ -675,6 +675,17 @@ export class Flags {
     },
   };
 
+  public static readonly javaFlightRecorderConfiguration: CommandFlag = {
+    constName: 'jfcFile',
```
Comment (jeromy-cannon) [inline src/commands/flags.ts]:
```suggestion
    constName: 'javaFlightRecorderConfiguration',
```
the constName should match the variable name.

File: src/commands/flags.ts [hunk 3]
```diff
@@ -675,6 +675,17 @@ export class Flags {
...
+    name: 'jfc',
```
Comment (jeromy-cannon) [inline src/commands/flags.ts]:
```suggestion
    name: 'jfr-config',
```
