### PR TITLE
fix: fix freeze timestamp for node add command

### LINKED ISSUE #326: Incorrect freeze timestamp used in node add
### Describe the bug

Current implementation `futureDate.setDate(futureDate.getDate() + (1 / 24 / 60))`
actually would set freeze time as exactly current time, instead of one minute layer.
This is due to both setDate and getDate are dealing with integer.
so `interger + (1 / 24 / 60)` resulted in the same integer, so the operation did not change
date or hours, giving the exactly current timestamp as freeze timestamp.

The transaction receipt if enabled would give error `FREEZE_START_TIME_MUST_BE_FUTURE`

### Describe the expected behavior

Should set correct timestamp and receive SUCEED as transaction receipt

### Whole JUnit/CLI Logs

```shell
No
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

* Fixed timestamp setting since SetDate and GetDate will not provide a unix timestamp, but a day number within a month

### Related Issues

* Closes #326

### CODE REVIEW

**Review by leninmehedy — DISMISSED** [review]

File: src/commands/node.mjs [hunk 1]
```diff
@@ -1467,9 +1470,13 @@ export class NodeCommand extends BaseCommand {
...
         .execute(client)
 
-      this.logger.debug(`Upgrade frozen with transaction id: ${freezeUpgradeTx.transactionId.toString()}`)
+      const freezeUpgradeReceipt = await freezeUpgradeTx.getReceipt(client)
+
+      this.logger.debug(`Upgrade frozen with transaction id: ${freezeUpgradeTx.transactionId.toString()}`,
+        freezeUpgradeReceipt.status.toString())
     } catch (e) {
       this.logger.error(`Error in freeze upgrade: ${e.message}`, e)
+      await sleep(360000)
```
Comment (jeromy-cannon) [inline src/commands/node.mjs:1479]: what is the purpose for sleeping for 6 minutes?  when it throws the error, then it will exit the app and stop processing.

**Review by jeromy-cannon — CHANGES_REQUESTED** [review]

File: src/commands/node.mjs (hunk 1 above)
Comment (JeffreyDallas) [reply src/commands/node.mjs]: was added during debug, removed it.

**Review by jeromy-cannon — APPROVED** [review]
