### PR TITLE
fix: flag check of node logs command and incorrect download source

### LINKED ISSUE #847: Flag `node-aliases-unparsed` did not work for `solo node logs` command
### Bill of Materials or CLI Version

_No response_

### Execution Environment

Local Node CLI

### Slf4j Logging Implementation

None

### To Reproduce

```markdown
npm run solo-test -- node logs -i node1,node2,node3

> @hashgraph/solo@0.99.0 solo-test
> node --no-deprecation --no-warnings --loader ts-node/esm solo.ts node logs -i node1,node2,node3


******************************* Solo *********************************************
Version			: 0.99.0
Kubernetes Context	: kind-solo-cluster
Kubernetes Cluster	: kind-solo-cluster
**********************************************************************************
✖ No value set for required flag: node-aliases-unparsed
◼ Get node logs and configs
*********************************** ERROR *****************************************
Error in downloading log from nodes: No value set for required flag: node-aliases-unparsed
***********************************************************************************

```

Also the download log command did not work, there were errors in the solo.log

```
"copyFrom[network-node2-0,8b81721b-11a3-4dc6-9254-6f86a9d5264a]: [srcPath=/opt/hgcapp/services-hedera/HapiApp2.0/network-node2-0.zip, destDir=/Users/jeffrey/.solo/logs/solo-e2e/2024-11-19T16-17-39-049Z]"
"execContainer[network-node1-0,194defb8-e603-425b-b18e-d96ff63f3c1e]: Failure occurred"
"failed to download logs from pod network-node1-0 unable to check path in 'network-node1-0':root-container' - /opt/hgcapp/services-hedera/HapiApp2.0/network-node1-0.zip: ls: cannot access '/opt/hgcapp/services-hedera/HapiApp2.0/network-node1-0.zip': No such file or directory\n:execContainer[network-node1-0,194defb8-e603-425b-b18e-d96ff63f3c1e]: Failure occurred"
"getNodeLogs(network-node1-0): ...end"
"execContainer[network-node1-0,194defb8-e603-425b-b18e-d96ff63f3c1e]: connection closed"
"execContainer[network-node2-0,b22d4417-2b68-4fe4-9f62-b12fbb524082]: begin... command=[ls -la /opt/hgcapp/services-hedera/HapiApp2.0/network-node2-0.zip]"
"execContainer[network-node2-0,b22d4417-2b68-4fe4-9f62-b12fbb524082]: running..."
"execContainer[network-node2-0,b22d4417-2b68-4fe4-9f62-b12fbb524082]: connection established"
"execContainer[network-node2-0,b22d4417-2b68-4fe4-9f62-b12fbb524082]: received message"
"execContainer[network-node2-0,b22d4417-2b68-4fe4-9f62-b12fbb524082]: Failure occurred"
"failed to download logs from pod network-node2-0 unable to check path in 'network-node2-0':root-container' - /opt/hgcapp/services-hedera/HapiApp2.0/network-node2-0.zip: ls: cannot access '/opt/hgcapp/services-hedera/HapiApp2.0/network-node2-0.zip': No such file or directory\n:execContainer[network-node2-0,b22d4417-2b68-4fe4-9f62-b12fbb524082]: Failure occurred"
"getNodeLogs(network-node2-0): ...end"
"\u001b[32m✔\u001b[39m Initialize"
```

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

* Fixed unparsed node alias node assigned error
* Fixed the incorrect log download source directory
* Added a unit check to check if download is working

### Related Issues

* Closes #847

### CODE REVIEW

File: src/commands/node/configs.ts [hunk 1]
```diff
@@ -238,7 +238,8 @@ export const logsConfigBuilder = function (argv, ctx, task) {
     /** @type {{namespace: string, nodeAliases: NodeAliases}} */
     const config = {
         namespace: this.configManager.getFlag(flags.namespace),
-        nodeAliases: helpers.parseNodeAliases(this.configManager.getFlag(flags.nodeAliasesUnparsed))
+        nodeAliases: helpers.parseNodeAliases(this.configManager.getFlag(flags.nodeAliasesUnparsed)),
```
Comment (jeromy-cannon) [inline src/commands/node/configs.ts:241]: need to update the @type on line 238

**Review by jeromy-cannon — APPROVED** [review]
