### PR TITLE
fix: node add/delete helm upgrade failure

### LINKED ISSUE #1624: E2E node add test failed with using local solo-chart
### Describe the bug

```
✖ failed to upgrade chart solo-deployment: Command exit with error code 1: /Users/jeffrey/.solo/bin/helm upgrade -n node-add solo-deployment /Users/jeffrey/solo-charts/charts/solo-deployment --version 0.45.0
  --reuse-values  --set "hedera.nodes[0].accountId=0.0.3" --set "hedera.nodes[0].name=node1" --set "hedera.nodes[0].nodeId=0"  --set "hedera.nodes[1].accountId=0.0.4" --set "hedera.nodes[1].name=node2" --set
  "hedera.nodes[1].nodeId=1"  --set "hedera.nodes[2].accountId=0.0.5" --set "hedera.nodes[2].name=node3" --set "hedera.nodes[2].nodeId=2"  --values /Users/jeffrey/solo-charts/charts/solo-deployment/values.yaml
  --values /Users/jeffrey/solo/test/data/tmp/solo-node-transaction.yaml --kube-context kind-solo-e2e-c1
◼ Kill nodes
◼ Check node pods are running
◼ Populate serviceMap
◼ Fetch platform software into network nodes
◼ Download last state from an existing node
◼ Upload last saved state to new network node
◼ Setup network nodes
◼ Starting nodes
◼ Enable port forwarding for JVM debugger
◼ Check all nodes are ACTIVE
◼ Check all node proxies are ACTIVE
◼ Stake new node
◼ Trigger stake weight calculate
◼ Finalize

Error: UPGRADE FAILED: resource mapping not found for name: "network-node-monitor" namespace: "node-add" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

### Describe the expected behavior

Test should pass

### To Reproduce

SOLO_CLUSTER_DUALITY=1 ./test/e2e/dual-cluster/setup-dual-e2e.sh ; SOLO_TEST_CLUSTER=solo-e2e-c1 npm run test-e2e-node-add

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

* node add/delete helm upgrade failure

### Related Issues

* Closes #1624

### CODE REVIEW

File: version_test.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
 /**
  * SPDX-License-Identifier: Apache-2.0
  */
-export const TEST_LOCAL_HEDERA_PLATFORM_VERSION = 'v0.58.10';
+export const TEST_LOCAL_HEDERA_PLATFORM_VERSION = 'v0.59.2';
```
Comment (jeromy-cannon) [inline version_test.ts:4]: I was leaving the local hedera tests at v0.58.10 to test backwards compatibility.

Comment (JeffreyDallas) [reply version_test.ts]: Changed it back

**Review by jeromy-cannon — APPROVED** [review]
