### PR TITLE
fix: updates to accommodate haproxy changes in FST charts

### LINKED ISSUE #312: Bug: E2E Node Test fails in pipeline with `failed to recycle pod for podName haproxy-...`
- [ ] remove logic that recycles the haproxy node
- [ ] update the logic that checks the haproxy data plane api port 5555 and instead use PodCondition[Ready] once the liveness probe has been implemented

example: https://github.com/hashgraph/solo/actions/runs/9115293005/job/25061315664#step:16:256
```
console.log
    expect(received).resolves.toBeTruthy()
    
    Received promise rejected instead of resolved
    Rejected to value: [FullstackTestingError: Error starting node: failed to check proxy for 'node0' with localPort 30313: failed to recycle pod for podName haproxy-node0-6969f76c77-skm7s with localPort 30313: pods are not running after deletion with labels [app=haproxy-node0,fullstack.hedera.com/type=haproxy]]

      at log (src/core/logging.mjs:132:17)
          at Array.forEach (<anonymous>)

  console.log
    Error: expect(received).resolves.toBeTruthy()
    
    Received promise rejected instead of resolved
    Rejected to value: [FullstackTestingError: Error starting node: failed to check proxy for 'node0' with localPort 30313: failed to recycle pod for podName haproxy-node0-6969f76c77-skm7s with localPort 30313: pods are not running after deletion with labels [app=haproxy-node0,fullstack.hedera.com/type=haproxy]]
        at expect (/runner/_work/solo/solo/node_modules/expect/build/index.js:113:15)
        at Object.expect (/runner/_work/solo/solo/test/test_util.js:221:15)
        at Promise.then.completed (/runner/_work/solo/solo/node_modules/jest-circus/build/utils.js:298:28)
        at new Promise (<anonymous>)
        at callAsyncCircusFn (/runner/_work/solo/solo/node_modules/jest-circus/build/utils.js:231:10)
        at _callCircusTest (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:316:40)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at _runTest (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:[252](https://github.com/hashgraph/solo/actions/runs/9115293005/job/25061315664#step:16:253):3)
        at _runTestsForDescribeBlock (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:126:9)
        at _runTestsForDescribeBlock (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:121:9)
        at _runTestsForDescribeBlock (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:121:9)
        at _runTestsForDescribeBlock (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:121:9)
        at run (/runner/_work/solo/solo/node_modules/jest-circus/build/run.js:71:3)
        at runAndTransformResultsToJestFormat (/runner/_work/solo/solo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
        at jestAdapter (/runner/_work/solo/solo/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
        at runTestInternal (/runner/_work/solo/solo/node_modules/jest-runner/build/runTest.js:367:16)
        at runTest (/runner/_work/solo/solo/node_modules/jest-runner/build/runTest.js:444:34)

      at log (src/core/logging.mjs:133:17)
          at Array.forEach (<anonymous>)
```

- [ ] requires https://github.com/hashgraph/full-stack-testing/issues/852
- [ ] requires https://github.com/hashgraph/solo/issues/315

### PR DESCRIPTION
**Pull request by jeromy-cannon**
## Description

This pull request changes the following:

* use `Running` phase for proxy check during `solo network deploy`
* remove haproxy recycle pod logic, instead use waitForPodReady which uses the PodCondition[Ready] = true that the haproxy is now setting based on the startupProbe
* removed checkNetworkNodeProxyUp
* use in test cases HEDERA_PLATFORM_VERSION = 'v0.49.0-alpha.2' since this is the first version to support FQDN correctly
* enhanced prepareAddressBookBase64 to convert FQDN to IP addresses to support Mirror Node
* enhanced nodeClient creation to set more robust timeouts and backoffs
* refactored getNodeServiceMap() to use a new class NetworkNodeServices to strongly type variables and give it more attributes that can be provide more reuse
* updated prepareConfigTxt() to use accountId from services instead of dynamically constructing it which could be wrong in some scenarios
* added the ability to set a local environment variable `SOLO_FST_CHARTS_DIR` to point to the developers FST chart directory for running tests locally against a chart that hasn't been released yet

### Related Issues

* Closes #312
* Relates to https://github.com/hashgraph/solo/issues/331

### CODE REVIEW

File: version.mjs [hunk 1]
```diff
@@ -21,5 +21,5 @@
 
 export const JAVA_VERSION = '21.0.1+12'
 export const HELM_VERSION = 'v3.14.2'
-export const FST_CHART_VERSION = 'v0.24.5'
-export const HEDERA_PLATFORM_VERSION = 'v0.48.0'
+export const FST_CHART_VERSION = 'v0.24.5' // TODO update after I tag the release
```
Comment (jeromy-cannon) [inline version.mjs:24]: TODO

File: package.json [hunk 2]
```diff
@@ -27,7 +27,7 @@
     "check": "remark . --quiet --frail && eslint .",
     "format": "remark . --quiet --frail --output && eslint --fix .",
     "test-setup": "./test/e2e/setup-e2e.sh",
-    "test-coverage": "npm run test && npm run test-setup &&  npm run test-e2e-all && npm run report-coverage"
+    "test-coverage": "npm run test-setup &&  npm run test-e2e-all && npm run report-coverage"
```
Comment (jeromy-cannon) [inline package.json:30]: revert

File: test/e2e/e2e_node_util.js [hunk 3]
```diff
@@ -70,10 +75,10 @@ export function e2eNodeKeyRefreshAddTest (keyFormat, testName, mode, releaseTag
     }, 120000)
 
     afterAll(async () => {
-      await k8.deleteNamespace(namespace)
+      // await k8.deleteNamespace(namespace)
```
Comment (jeromy-cannon) [inline test/e2e/e2e_node_util.js:78]: revert

File: test/e2e/e2e_node_util.js [hunk 4]
```diff
@@ -70,10 +75,10 @@ export function e2eNodeKeyRefreshAddTest (keyFormat, testName, mode, releaseTag
...
     }, 120000)
 
-    describe(`Node should have started successfully [mode ${mode}, release ${releaseTag}, keyFormat: ${keyFormat}]`, () => {
+    describe.skip(`Node should have started successfully [mode ${mode}, release ${releaseTag}, keyFormat: ${keyFormat}]`, () => {
```
Comment (jeromy-cannon) [inline test/e2e/e2e_node_util.js:81]: revert

File: test/e2e/e2e_node_util.js [hunk 5]
```diff
@@ -92,7 +99,7 @@ export function e2eNodeKeyRefreshAddTest (keyFormat, testName, mode, releaseTag
       }, 60000)
     })
 
-    describe(`Node should refresh successfully [mode ${mode}, release ${releaseTag}, keyFormat: ${keyFormat}]`, () => {
+    describe.skip(`Node should refresh successfully [mode ${mode}, release ${releaseTag}, keyFormat: ${keyFormat}]`, () => {
```
Comment (jeromy-cannon) [inline test/e2e/e2e_node_util.js:102]: revert

**Review by leninmehedy — APPROVED** [review]
Thanks
